name: Deploy JSON
on:
  push:
    branches: [main, master]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Upload site
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./
